import { chromium } from 'playwright'
const D='/private/tmp/claude-501/-Users-kapana-Desktop-Tutor/f63e2b62-9fdc-47e2-b335-c08d43dea4a4/scratchpad'
const br = await chromium.launch()
const ctx = await br.newContext({viewport:{width:1440,height:900}})
const p = await ctx.newPage(); p.setDefaultNavigationTimeout(90000); p.setDefaultTimeout(30000)
const errs=[]; p.on('pageerror', e=>errs.push(String(e).slice(0,100)))
await p.goto('https://mcodne.ge/signin',{waitUntil:'domcontentloaded'})
await p.waitForSelector('input[type="email"]',{timeout:40000})
await p.fill('input[type="email"]','admin@mcodne.ge')
await p.fill('input[type="password"]', process.env.ADM_PW)
await p.getByRole('button', { name: 'შესვლა', exact: true }).first().click()
await p.waitForTimeout(8000)
console.log('role:', await p.evaluate(async()=>{const r=await fetch('/api/me');return (await r.json())?.user?.role}))
await p.goto('https://mcodne.ge/admin',{waitUntil:'domcontentloaded'})
await p.waitForSelector('aside nav button',{timeout:40000}); await p.waitForTimeout(3000)
const nav = await p.evaluate(()=>[...document.querySelectorAll('aside nav > div')].map(g=>
  ((g.querySelector('div')?.textContent||'').trim()) + ': ' + [...g.querySelectorAll('button')].map(b=>b.textContent.trim()).join(' · ')))
console.log(nav.join('\n'))
await p.evaluate(()=>{window.location.hash='integrations'}); await p.waitForTimeout(5000)
const f = await p.evaluate(()=>({head:(document.querySelector('main')?.innerText||'').slice(0,50).replace(/\n/g,' | '),
  vals:[...document.querySelectorAll('main input, main textarea')].map(e=>(e.value||'').length).filter(n=>n>0)}))
console.log('tab:', f.head, '| filled fields (chars):', f.vals.join(', '))
console.log('GA on site:', await p.evaluate(async()=>{const x=await fetch('/');return (await x.text()).includes('G-4WFNGD5WNX')}))
console.log('page errors:', errs.length?errs[0]:'none')
await p.screenshot({path:`${D}/final-admin.png`})
await br.close(); process.exit(0)
