#!/usr/bin/env node
// Regenerates docs/MAP.md — the symbol index.
//
// ⚠️ WHY THIS EXISTS. `lib/` is 126 files flat with 859 exported symbols, and
// the request family alone is 13 files whose names differ by a suffix
// (`requests` vs `requestsServer` vs `requestJobs`). Finding "which file
// exports X" cost a grep-and-guess every time — `requestsViewer` lives in
// `requestsServer.ts`, not in `requests.ts`, and that is not guessable.
//
// One `grep` in this file answers it. Regenerate after adding or moving an
// export:  npm run map
//
// It is DERIVED, never hand-edited: a stale hand-written map is worse than no
// map, because it is believed.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const ROOTS = ['lib', 'components', 'app']
const SKIP = /node_modules|\.next|\/tests?\//

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (SKIP.test(p)) continue
    if (statSync(p).isDirectory()) walk(p, out)
    else if (/\.tsx?$/.test(p)) out.push(p)
  }
  return out
}

const EXPORT = /^export\s+(?:async\s+)?(?:function|const|class|type|interface|enum)\s+(\w+)/gm
const rows = []
for (const root of ROOTS) {
  for (const f of walk(root)) {
    const src = readFileSync(f, 'utf8')
    const syms = [...src.matchAll(EXPORT)].map(m => m[1])
    if (syms.length) rows.push([f, syms])
  }
}

const bySym = new Map()
for (const [f, syms] of rows) for (const s of syms) {
  if (!bySym.has(s)) bySym.set(s, [])
  bySym.get(s).push(f)
}

const out = [
  '<!-- GENERATED by scripts/build-map.mjs — do not edit. Run: npm run map -->',
  '',
  '# Where every export lives',
  '',
  `${bySym.size} symbols across ${rows.length} files. \`grep\` the name you need.`,
  '',
  '| symbol | file |',
  '| --- | --- |',
]
for (const s of [...bySym.keys()].sort((a, b) => a.localeCompare(b))) {
  out.push(`| \`${s}\` | ${bySym.get(s).map(f => `\`${f}\``).join(' · ')} |`)
}
// ── the SCHEMA half ───────────────────────────────────────────────────────
// ⚠️ THE SECOND THING THAT COSTS A ROUND TRIP. Prisma field names are not
// guessable from the UI word: the price on a Booking is `price`, on a
// RequestOffer it is `priceGel`; ServiceProfile has no `visible` and Category
// has no `hidden`. Four queries failed on guesses in one session. The field
// list belongs beside the symbol list.
const schema = readFileSync('prisma/schema.prisma', 'utf8')
const models = [...schema.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)].map(m => {
  const fields = [...m[2].matchAll(/^\s{2}(\w+)\s+(\S+)/gm)]
    .filter(f => !['@@index', '@@unique', '@@map', '@@id'].includes(f[1]))
    .map(f => `${f[1]}:${f[2].replace(/\?$/, '?')}`)
  return [m[1], fields]
})
out.push('', '---', '', '# Prisma models and their fields', '',
  `${models.length} models. The UI word is not the column name — check here before writing a query.`, '')
for (const [name, fields] of models.sort((a, b) => a[0].localeCompare(b[0]))) {
  out.push(`**${name}** — ${fields.join(' · ')}`, '')
}

writeFileSync('docs/MAP.md', out.join('\n') + '\n')
console.log(`docs/MAP.md — ${bySym.size} symbols, ${rows.length} files, ${models.length} models`)
