/**
 * Delete the synthetic test accounts from production. ONE TIME, and by an
 * EXPLICIT LIST — never by a pattern.
 *
 *   npx tsx -r dotenv/config scripts/purge-test-accounts.ts          (dry run)
 *   npx tsx -r dotenv/config scripts/purge-test-accounts.ts --apply  (deletes)
 *
 * ⚠️ THIS WRITES TO PRODUCTION. There is no sandbox database; a local shell's
 * DATABASE_URL points at the live one.
 *
 * WHY AN EXPLICIT LIST AND NOT A RULE. The obvious rule — „no bookings, no
 * messages" — would have taken about twenty REAL people with it: someone who
 * signed up last week and has not booked yet looks identical to a bot under
 * that predicate. „No history" is not evidence of being fake, it is evidence of
 * being new, and those are the visitors this marketplace is hardest pressed to
 * get. So every address below was read individually and is synthetic on its
 * face: a generated local part, an @example.* / @mcodne.test domain, a QA seed,
 * or one of the owner's own +test aliases.
 *
 * The script REFUSES to delete anything that has history it was not told to
 * expect. If a row here turns out to carry a real conversation or review, the
 * run aborts rather than guessing — the one outcome worse than leaving a bot in
 * the database is removing a person from it.
 */
import { prisma } from '../lib/prisma'

/** Every address to remove. Read one by one; see the header for the rule. */
const TARGETS = [
  // Generated by the Playwright harnesses (tests/*.mjs)
  'bt1783940081836@mcodne.test',
  'bt1783940266784@mcodne.test',
  't1783948414382@mcodne.test',
  't1783948689900@mcodne.test',
  'bt1785353123940@mcodne.test',
  // QA fixtures
  'qa-authshell-x1@example.com',
  'qa-authshell-6321@example.com',
  'bogus22600@example.invalid',
  'qa-r3@mcodne.ge',
  'qa-r4@mcodne.ge',
  'qa-p4@mcodne.ge',          // TUTOR — „ფასის ტესტი", paused, 1 offering
  // The owner's own throwaway aliases
  'webinfinity12+test1@gmail.com',
  'webinfinity12+mcodnetest@gmail.com',
  // Junk signup — misspelled domain, never used
  'asdqrwq@farg.gmial.com',
  // The ONLY one with history: a single test booking, deleted with it.
  // Confirmed by the owner 2026-08-04.
  'test+1785057257966@example.com',
]

/**
 * Accounts that must survive no matter what a future edit to TARGETS says.
 * A tester is only useful if it still exists.
 */
const PROTECTED = [
  'lukakapanadze313@gmail.com',       // expert-side tester (and an ADMIN)
  'grubela222@gmail.com',             // client-side tester
  'admin@mcodne.ge',                  // second admin
  'webinfinity12@gmail.com',          // the owner's expert account
]

const APPLY = process.argv.includes('--apply')

async function main() {
  console.log(APPLY ? '⚠️  APPLY — ვშლი\n' : '👀 DRY RUN — არაფერს ვშლი (--apply გასაშვებად)\n')

  let deletedUsers = 0
  let deletedBookings = 0

  for (const email of TARGETS) {
    if (PROTECTED.includes(email)) throw new Error(`${email} is PROTECTED and must never be in TARGETS`)

    const u = await prisma.user.findUnique({
      where: { email },
      select: {
        id: true, email: true, fullName: true, role: true,
        tutor: { select: { id: true, _count: { select: { bookings: true, reviews: true, consultations: true, availability: true } } } },
        _count: { select: { bookingsAsStudent: true, sentMessages: true, receivedMessages: true, reviewsGiven: true } },
      },
    })
    if (!u) { console.log(`   —  ${email} — არ არსებობს (უკვე წაშლილია)`); continue }

    const asStudent = u._count.bookingsAsStudent
    const asTutor = u.tutor?._count.bookings ?? 0
    const msgs = u._count.sentMessages + u._count.receivedMessages
    const reviews = u._count.reviewsGiven + (u.tutor?._count.reviews ?? 0)

    // The ONE account allowed to carry a booking. Everything else must be clean,
    // or something is not what this list thought it was.
    const bookingsAllowed = email === 'test+1785057257966@example.com' ? 1 : 0
    if (asStudent + asTutor > bookingsAllowed || msgs > 0 || reviews > 0) {
      throw new Error(
        `ABORT — ${email} carries history this script did not expect ` +
        `(ჯავშანი ${asStudent + asTutor}, მესიჯი ${msgs}, შეფასება ${reviews}). ` +
        'Re-check by hand before touching it.',
      )
    }

    console.log(
      `   ${APPLY ? '🗑' : '·'}  ${u.role.padEnd(7)} ${email.padEnd(36)} ${u.fullName || '—'}` +
      (u.tutor ? `  [ექსპერტი: ${u.tutor._count.consultations} სერვისი, ${u.tutor._count.availability} დრო]` : '') +
      (asStudent ? `  [${asStudent} ჯავშანი — წაიშლება]` : ''),
    )

    if (!APPLY) continue

    // Bookings hold the student with onDelete: Restrict (deliberate — see the
    // schema note), so the booking goes first. Its messages, reschedule rows and
    // dispute cascade with it; a review would not, hence the guard above.
    if (asStudent > 0) {
      const res = await prisma.booking.deleteMany({ where: { studentId: u.id } })
      deletedBookings += res.count
    }
    // TutorProfile, sessions, notifications, favorites, OTP and reset tokens all
    // cascade from the user row.
    await prisma.user.delete({ where: { id: u.id } })
    deletedUsers++
  }

  console.log(`\n${APPLY ? `✅ წაიშალა: ${deletedUsers} ანგარიში, ${deletedBookings} ჯავშანი` : 'გასაშვებად: --apply'}`)

  const left = await prisma.user.count()
  console.log(`დარჩა მომხმარებელი: ${left}`)
  for (const p of PROTECTED) {
    const ok = await prisma.user.findUnique({ where: { email: p }, select: { role: true } })
    console.log(`   ${ok ? '✅' : '❌ დაკარგულია!'} ${p}${ok ? ` (${ok.role})` : ''}`)
  }
}

main()
  .catch(e => { console.error('\n❌', e instanceof Error ? e.message : e); process.exitCode = 1 })
  .finally(() => prisma.$disconnect())
